[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = [
	"pragma: no cover",
	"raise NotImplementedError",
	"if __name__ == .__main__.:",
	"if typing.TYPE_CHECKING:",
]

[tool.pytest.ini_options]
faulthandler_timeout = 15
pythonpath = '.'

[tool.ruff]
select = ["E", "F", "B", "UP", "C4", "SIM"]
ignore = ["E501"]
target-version = "py39"
